collision_alpha: 0.1
collision_size: 1.0
collision_zone_alpha: 0.075
collision_zone_base_diameter: 0.025
color_scheme:
  arena_turtlebot3_burger: tab:grey
  cadrl_turtlebot3_burger: tab:olive
  dwa_jackal: tab:red
  dwa_turtlebot3_burger: tab:red
  guldenring_jackal: tab:brown
  guldenring_turtlebot3_burger: tab:brown
  mpc_jackal: tab:green
  mpc_turtlebot3_burger: tab:green
  navrep_jackal: tab:purple
  rosnav_jackal: tab:orange
  rosnav_turtlebot3_burger: tab:orange
  teb_jackal: tab:cyan
  teb_turtlebot3_burger: tab:cyan
goal_marker: '*'
goal_point_color: tab:brown
goal_size: 20
labels:
  arena_turtlebot3_burger: ARENA
  cadrl_turtlebot3_burger: CADRL
  dwa_jackal: DWA
  dwa_turtlebot3_burger: DWA
  guldenring_jackal: "G\xFCldenring"
  guldenring_turtlebot3_burger: "G\xFCldenring"
  mpc_jackal: MPC
  mpc_turtlebot3_burger: MPC
  navrep_jackal: NAVREP
  rosnav_jackal: ROSNAV
  rosnav_turtlebot3_burger: ROSNAV
  teb_jackal: TEB
  teb_turtlebot3_burger: TEB
leave_out_metric:
- cusps
leave_out_planner:
- rlca_subsampling
- drl_subsampling
most_recent_file: data_jackal.json
obstacle_color: black
obstacle_radius: 0.3
path_alpha: 0.3
path_arrow_color: black
path_arrow_size: 5
path_size: 0.1
plot_barplot_alpha: 1.0
plot_barplot_capsize: 0.1
plot_barplot_errorbars: false
plot_barplot_errorcolor: black
plot_barplot_width: 0.5
plot_collision_zones: true
plot_collisions: true
plot_obs_in_one: true
plot_progression: false
plot_qualitative: true
plot_qualitative_axes: true
plot_qualitative_axes_size: 8
plot_qualitative_legend: true
plot_qualitative_legend_location: upper left
plot_qualitative_title: true
plot_qualitative_title_size: 16
plot_quantitative: false
plot_quantitative_axes_label_size: 12
plot_quantitative_axes_tick_size: 10
plot_quantitative_labels:
  angle_over_length: Angle over Length
  collision: Collisions
  computation_time: Computation Time in [s]
  cusps: Cusps
  jerk: Movement Jerk in [$\frac{m}{s^{3}}$]
  max_clearing_distance: Max. Clearing Distance in [m]
  max_curvature: Max. Curvature
  mean_clearing_distance: Mean Clearing Distance in [m]
  median_clearing_distance: Median Clearing Distance in [m]
  min_clearing_distance: Min. Clearing Distance in [m]
  normalized_curvature: Normalized Curvature
  obstacle_number: Obstacle Number
  path_length: Path Length in [m]
  planner: Planner
  roughness: Path Roughness
  success: Success Rate
  time: Time Traveled in [s]
plot_quantitative_legend: true
plot_quantitative_legend_location: upper left
plot_quantitative_suptitle: true
plot_quantitative_suptitle_size: 16
plot_quantitative_title: true
plot_quantitative_title_size: 10
plot_quantitative_violin: false
plot_quantitative_violin_inner: point
plot_quantitative_ygrid: true
plot_success_alpha: 1.0
plot_success_collision_color: tab:red
plot_success_success_color: tab:green
plot_success_time_out_color: tab:blue
plot_success_width: 0.5
progression_size: 3
progression_steps: 20
specified_data_filename: null
specify_data: false
start_marker: ^
start_point_color: tab:grey
start_size: 20
