#common
obstacle_range: 2.5 #default = 2.5
raytrace_range: 3.0 #default = 3.0
# footprint: [[0.185, 0.185], [0.185, -0.185], [-0.185, -0.185], [-0.185, 0.185]]
footprint: [[0.4,0.0],[0.35,0.35],[-0.2,0.4],[-0.45,0.0],[-0.2,-0.4],[0.35,-0.35]]
footprint_padding: 0.1

inflater_layer:
  inflation_radius: 0.25

map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

plugins:
  - { name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
  - { name: inflater_layer, type: "costmap_2d::InflationLayer" }

obstacles_layer:
  observation_sources: scan
  scan:
    {
      sensor_frame: front_laser,
      data_type: LaserScan,
      topic: scan,
      marking: true,
      clearing: true,
      min_obstacle_height: -2.0,
      max_obstacle_height: 2.0,
      obstacle_range: 2.5,
      raytrace_range: 3.0,
    }
